#!/bin/bash

cp -f .config ./src/
cd ./src
yes '' | make oldconfig
make clean

CORES=`getconf _NPROCESSORS_ONLN`
if (( ${CORES} > 1 ));
  then
    let CORES--
fi
echo "make -j ${CORES} deb-pkg LOCALVERSION=-custom"
eval "make -j ${CORES} deb-pkg LOCALVERSION=-custom"
